### ISSUE TITLE
Hue Cos & Sin Issue?

### ISSUE THREAD

**Issue by torridgristle** [DragWx/PalGen#2]
Currently it uses sin for I and cos for Q, but I think it should be cos for I and sin for Q judging by what little I know of cylindrical transformations of luma + opposing chroma models. I'm basing it on http://www.brucelindbloom.com/index.html?Eqn_LCH_to_Lab.html and http://www.brucelindbloom.com/index.html?Eqn_Lab_to_LCH.html and my own implementation of YUV hue + chroma adjustments by using these maths with YUV instead of Lab which is

vec3 RGBtoYCHuv(vec3 Photo) {
    Photo *= RGB_to_YUV;
    float Chroma = sqrt((Photo.y*Photo.y)+(Photo.z*Photo.z));
    float Hue = atan(Photo.z,Photo.y);
    Photo = vec3(Photo.x,Chroma,Hue);
    return Photo;
}

vec3 YCHuvtoRGB(vec3 Photo) {
    Photo = vec3(Photo.x,Photo.y*cos(Photo.z),Photo.y*sin(Photo.z));
    Photo *= YUV_to_RGB;
    return Photo;
}

I mean it doesn't look wrong with the current code but it seems inconsistent with what I expect and I don't fully understand what's going on so I worry that something is being done wrong somewhere.

**Comment by DragWx** [comment]
It doesn't matter which uses which, as long as the formulas are consistent. For instance:

If someone's converting an angle to coordinates like this:
```
X = sin(A)
Y = cos(A)
```
The way you convert X and Y back to an angle is like this (since it looks like you're writing a shader):
```
atan(X,Y)
```

However, if someone's converting an angle to coordinates like *this*:
```
X = cos(A)
Y = sin(A)
```
You would recover the angle by doing *this* instead:
```
atan(Y,X)
```

x, y, angle or i, q, hue, it's all still trigonometry at the end of the day! :P
